spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/glimon
    username: root
    password: toor
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
server:
    port: 8081
    error:
        include-message: always
    servlet:
      context-path: /caseta
springdoc:
    api-docs.path: /api-docs
